spring:
  datasource:
    url: jdbc:postgresql://dpg-cnd4t1ed3nmc738jm8t0-a.oregon-postgres.render.com:5432/web_hosting_provider_db
    username: user
    password: Njwws6orLB6plu5B8rbpYLAKMim0jONO
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: 1o4RbVqRTa+lEWCx9ZKPNProd7NINpEPB46grgr2mW8=
  accessTokenLife: 5
  refreshTokenLife: 30
  issuer: www.novatechzone.com
springdoc:
  paths-to-match: /**